[target.aarch64-linux-android]
linker = "/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android33-clang"

[target.armv7-linux-androideabi]
linker = "/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi33-clang"

[target.i686-linux-android]
linker = "/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android33-clang"

[target.x86_64-linux-android]
linker = "/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android33-clang"

[env]
AR_aarch64-linux-android="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
CC_aarch64-linux-android="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android33-clang"
CXX_aarch64-linux-android="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android33-clang++"

AR_armv7-linux-androideabi="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
CC_armv7-linux-androideabi="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi33-clang"
CXX_armv7-linux-androideabi="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi33-clang++"

AR_i686-linux-android="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
CC_i686-linux-android="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android33-clang"
CXX_i686-linux-android="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android33-clang++"

AR_x86_64-linux-android="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
CC_x86_64-linux-android="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android33-clang"
CXX_x86_64-linux-android="/Users/shubhampanchal/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android33-clang++"